import React from 'react';
import {Composition} from 'remotion';
import {DeckVideo} from './video';
import type {Storyboard} from './types';

const fallback: Storyboard = {
  schemaVersion: 1,
  source: 'html-slide',
  title: 'html-slide video',
  language: 'ko',
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 150,
  design: {
    paletteId: 'fallback',
    datavizId: 'fallback',
    typographyId: 'fallback',
    palette: {
      paper: '#08111f',
      ink: '#f7f9fc',
      muted: '#b2bfd0',
      accent: '#54a8ff',
      surface: '#111d2e',
      line: '#53677f'
    },
    dataviz: {
      'viz-1': '#4ba3ff',
      'viz-2': '#ff8a3d',
      'viz-3': '#4ed69c',
      'viz-4': '#b985ff',
      'viz-5': '#f5c451',
      'viz-6': '#ff6fa8'
    }
  },
  scenes: [{
    id: 'placeholder',
    index: 0,
    title: 'Storyboard input required',
    summary: 'Generate props with tools/compose_video.py.',
    communicationGoal: 'Provide a storyboard generated by tools/compose_video.py',
    intent: 'thesis',
    layout: 'hero',
    theme: 'tech',
    blocks: [{
      id: 'message',
      module: 'statement',
      data: {text: 'Use --props=storyboard.json when rendering.'}
    }],
    slots: {main: ['message']},
    cues: [],
    startFrame: 0,
    durationFrames: 150,
    transitionFrames: 0
  }]
};

export const VideoRoot: React.FC = () => (
  <Composition
    id="DeckVideo"
    component={DeckVideo}
    durationInFrames={fallback.durationInFrames}
    fps={fallback.fps}
    width={fallback.width}
    height={fallback.height}
    defaultProps={fallback}
    calculateMetadata={({props}) => ({
      durationInFrames: props.durationInFrames,
      fps: props.fps,
      width: props.width,
      height: props.height
    })}
  />
);
