import React from 'react';
import {Composition} from 'remotion';
import {DeckVideo, type Storyboard} from './video';

const fallback: Storyboard = {
  schemaVersion: 1,
  source: 'html-slide',
  title: 'html-slide video',
  language: 'ko',
  fps: 30,
  width: 1920,
  height: 1080,
  durationInFrames: 150,
  scenes: [{
    id: 'placeholder',
    index: 0,
    title: 'Storyboard input required',
    summary: '',
    communicationGoal: 'Provide a storyboard generated by tools/compose_video.py',
    intent: 'thesis',
    layout: 'hero',
    theme: 'tech',
    style: {},
    blocks: [{id: 'message', module: 'statement', data: {text: 'Use --props=storyboard.json when rendering.'}}],
    cues: [],
    startFrame: 0,
    durationFrames: 150,
    transitionFrames: 0
  }]
};

export const VideoRoot: React.FC = () => {
  return (
    <Composition
      id="DeckVideo"
      component={DeckVideo}
      durationInFrames={fallback.durationInFrames}
      fps={fallback.fps}
      width={fallback.width}
      height={fallback.height}
      defaultProps={{storyboard: fallback}}
      calculateMetadata={({props}) => ({
        durationInFrames: props.storyboard.durationInFrames,
        fps: props.storyboard.fps,
        width: props.storyboard.width,
        height: props.storyboard.height
      })}
    />
  );
};
